#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define RGB_MATRIX_STARTUP_HUE 160
#define RGB_MATRIX_STARTUP_SPD 64

// not good in general. testing NMS macro
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 0
